const el =document.getElementById('content')
var root = ReactDOM.createRoot(el)
var h1 = React.createElement('h1', null, null, 'Hello World')
var div = React.createElement('div', null, null, h1, h1)
root.render(div)